// @flow

import React, { useEffect } from 'react'
import { css } from 'goober'
import Body from '../components/Body.js'
import MarkdownText from '../components/MarkdownText.js'
import View from '../components/View.js'
import Logo from '../components/Logo.js'
import Link from '../components/Link.js'

const styles = {
  page: css`
    align-self: stretch;
    height: 100%;
    overflow-y: scroll;

    > div {
      max-width: 720px;
      margin: 0 auto;
      width: 100%;
    }

    .link-home {
      position: fixed;
      top: 9px;
      left: 14px;
      padding: 0;
      background-color: transparent;
    }

    @media (max-width: 877px) {
      padding-top: 47px;
      padding-left: 20px;
      padding-right: 20px;

      .link-home {
        position: absolute;
      }
    }

    li::marker {
      color: #d9d9d9;
      font-weight: 700;
    }

    a[id] {
      font-weight: 700;
    }

    strong {
      color: rgb(60, 127, 247);
      font-weight: 700;
    }

    li li {
      list-style-type: lower-alpha;
    }

    li li li {
      list-style-type: lower-roman;
    }
  `,
}

const markdown = `
## PRIVACY POLICY
 
Effective date: 12/6/2023
 
1. <a id="introduction" href="#introduction">Introduction</a>
 
  Welcome to **chatbro.online**.
   
  Taylor Goolsby (“**us**”, “**we**”, or “**our**”) operates [chatbro.online](https://chatbro.online) (hereinafter referred together as “**Services**”, individually “**Service**”).
   
  Our Privacy Policy governs your visit to chatbro.online, and explains how we collect, safeguard and disclose information that results from your use of our Services. 
   
  We use your data to provide and improve our Services. By using our Services, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
   
  Our Terms and Conditions (“**Terms**”) govern all use of our Services and together with the Privacy Policy constitutes your agreement with us (“**Agreement**”).
 
2. <a id="definitions" href="#definitions">Definitions</a>
 
  **SERVICES** means the chatbro.online website operated by Taylor Goolsby.
   
  **PERSONAL DATA** means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
   
  **USAGE DATA** is data collected automatically either generated by the use of our Services or from our Services infrastructure itself (for example, the duration of a page visit).
   
  **COOKIES** are small files stored on your device (computer or mobile device).
   
  **DATA CONTROLLER** means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.
   
  **DATA PROCESSORS (OR SERVICE PROVIDERS)** means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.
   
  **DATA SUBJECT** is any living individual who is the subject of Personal Data.
   
  **THE USER** is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
 
3. <a id="information-collection-use" href="#information-collection-use">Information Collection and Use</a>
 
  We collect several different types of information for various purposes to provide and improve our Services to you.
 
4. <a id="types-of-data-collected" href="#types-of-data-collected">Types of Data Collected</a>
 
  **Personal Data**
  <br/>
  While using our Services, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“**Personal Data**”). Personally identifiable information may include, but is not limited to:
   
  1. Email address
  
  2. First name and last name
  
  3. Phone number
  
  4. Address, State, Province, ZIP/Postal code, City 
  
  5. Cookies and Usage Data
   
  We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.
   
  **Usage Data**
  <br/>
  We may also collect information that your browser sends whenever you visit our Services or when you access our Services by or through a mobile device (“**Usage Data**”).
   
  This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Services that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
   
  When you access our Services with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.

  **Location Data**
  <br/>
  We may use and store information about your location if you give us permission to do so (“**Location Data**”). We use this data to provide features of our Services, to improve and customize our Services.
   
  You can enable or disable location services when you use our Services at any time by way of your device settings.
   
  **Tracking Cookies Data**
  <br/>
  We use cookies and similar tracking technologies to track the activity on our Services and we hold certain information.
   
  Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Services.
   
  You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Services.
   
  Examples of Cookies we use:

  1. **Session Cookies:** We use Session Cookies to operate our Services.
  
  2. **Preference Cookies:** We use Preference Cookies to remember your preferences and various settings.
  
  3. **Security Cookies:** We use Security Cookies for security purposes.
  
  4. **Advertising Cookies:** Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.
   
  **Other Data**
  <br/>
  While using our Services, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at place of residence and actual address, telephone number (work, mobile), details of documents on education, qualification, professional training, employment agreements, non-disclosure agreements, information on bonuses and compensation, information on marital status, family members, social security (or other taxpayer identification) number, office location and other data. 
 
5. <a id="use-of-data" href="#use-of-data">Use of Data</a>
 
  We use the collected data for various purposes:

  1. to provide and maintain our Services;
  
  2. to notify you about changes to our Services;
  
  3. to allow you to participate in interactive features of our Services when you choose to do so;
  
  4. to provide customer support;
  
  5. to gather analysis or valuable information so that we can improve our Services; 
  
  6. to monitor the usage of our Services;
  
  7. to detect, prevent and address technical issues;
  
  8. to fulfill any other purpose for which you provide it;
  
  9. to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;
  
  10. to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;
  
  11. to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;
  
  12. in any other way we may describe when you provide the information;
  
  13. for any other purpose with your consent. 
  
6. <a id="ai-model-training">AI Model Training</a>

    1. **Data Collection and Storage**: When you use our Services, we collect and store data generated through your use. This includes, but is not limited to, agent instructions, chat messages, file uploads, and other generated data. Similarly, data generated by End Users of your Client Application in conjunction with our Services is also collected and stored.

    2. **Restriction on AI Model Training**: The data collected will not be used for the training of AI models. This policy is in place to safeguard against the potential exposure of sensitive data to a broader public audience, which could compromise the trust and confidentiality of End Users.

    3. **Responsibility of Client Application Developers**:
        * **Recommendation Against AI Model Training**: We advise developers of Client Applications against using the collected data for AI model training. However, this is a recommendation and not an enforceable mandate.
        * **Disclosure Requirement**: Developers must transparently disclose to their End Users if they use such data for AI model training.
        * **Liability**: Our company is not liable for any misuse of data by developers of Client Applications.

    4. **Permission-Based Use for AI Model Training**: We reserve the right to use collected data for AI model training if we receive explicit permission from you.

7. <a id="retention-of-data" href="#retention-of-data">Retention of Data</a>
 
  We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
   
  We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Services, or we are legally obligated to retain this data for longer time periods.
 
8. <a id="transfer-of-data" href="#transfer-of-data">Transfer of Data</a>
 
  Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
   
  If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there.
   
  Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
   
  Grainstack will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
 
9. <a id="disclosure-of-data" href="#disclosure-of-data">Disclosure of Data</a>
 
  We may disclose personal information that we collect, or you provide:
   
  1. **Disclosure for Law Enforcement.**
    <br/>
    Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.
    
  2. **Business Transaction.**
    <br/>
    If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.
    
  3. **Other cases. We may disclose your information also:**
   
    1. to our subsidiaries and affiliates;
    
    2. to contractors, service providers, and other third parties we use to support our business;
    
    3. to fulfill the purpose for which you provide it;
    
    4. for the purpose of including your company’s logo on our website;
    
    5. for any other purpose disclosed by us when you provide the information;
    
    6. with your consent in any other cases;
    
    7. if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.

10. <a id="handling-of-passwords">Handling and Storage of Sensitive Information</a>

  1. **User Passwords**
    <br/>
    We prioritize the security of your account. Each user's password is protected through a slow hashing function, combined with a unique salt for every user. This method ensures that your password is stored securely and is safeguarded against unauthorized access.
    We do not have access to your plain-text password, and under no circumstance will we ask for your password outside the secure login process.

  2. **Third-Party API Keys**
    <br/>
    If our service requires integration with third-party APIs, we will store your API keys in an encrypted form. This encryption is designed to prevent unauthorized access and to ensure that your keys remain confidential.
    The encrypted API keys are used solely for the purpose of providing the services that require these integrations, and we ensure to implement robust security measures to protect these keys.

10. <a id="security-of-data" href="#security-of-data">Security of Data</a>
 
  * We employ industry-standard security measures to protect your personal information and credentials. This includes, but is not limited to, secure server hosting, and firewall protection.
  * The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
 
11. <a id="gdpr" href="#gdpr">Your Data Protection Rights Under General Data Protection Regulation (GDPR)</a>
 
  If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR. – See more at https://eur-lex.europa.eu/eli/reg/2016/679/oj 
   
  We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
   
  If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at <Contact/>. 
   
  In certain circumstances, you have the following data protection rights:
   
  1. the right to access, update or to delete the information we have on you;
  
  2. the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;
  
  3. the right to object. You have the right to object to our processing of your Personal Data;
  
  4. the right of restriction. You have the right to request that we restrict the processing of your personal information;
  
  5. the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;
  
  6. the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;
   
  Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide our Services without some necessary data.
   
  You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
 
12. <a id="caloppa" href="#caloppa">Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)</a>
 
  CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law’s reach stretches well beyond California to require a person or company in the United States (and conceivable the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy. – See more at: https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/ 
   
  According to CalOPPA we agree to the following:
   
  1. users can visit our site anonymously;
  
  2. our Privacy Policy link includes the word “Privacy”, and can easily be found on the page specified above on the home page of our website;
  
  3. users will be notified of any privacy policy changes on our Privacy Policy Page;
  
  4. users are able to change their personal information by emailing us at <Contact/>. 
   
  Our Policy on “Do Not Track” Signals:
   
  We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked. 
   
  You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
 
13. <a id="ccpa" href="#ccpa">Your Data Protection Rights under the California Consumer Privacy Act (CCPA)</a>
 
  If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:
   
  1. **What personal information we have about you.** If you make this request, we will return to you:

      1. The categories of personal information we have collected about you.
      
      2. The categories of sources from which we collect your personal information.
      
      3. The business or commercial purpose for collecting or selling your personal information.
      
      4. The categories of third parties with whom we share personal information.
      
      5. The specific pieces of personal information we have collected about you.
      
      6. A list of categories of personal information that we have sold, along with the category of any other company we sold it to. If we have not sold your personal information, we will inform you of that fact.
      
      7. A list of categories of personal information that we have disclosed for a business purpose, along with the category of any other company we shared it with.
   
      Please note, you are entitled to ask us to provide you with this information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12 months.
   
  2. **To delete your personal information.** If you make this request, we will delete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate. 
   
  3. **To stop selling your personal information.** We do not sell your personal information for monetary consideration. However, under some circumstances, a transfer of personal information to a third party, or within our family of companies, without monetary consideration may be considered a “sale” under California law.
   
      If you submit a request to stop selling your personal information, we will stop making such transfers. If you are a California resident, to opt-out of the sale of your personal information, click “Do Not Sell My Personal Information” at the bottom of our home page to submit your request.
       
      Please note, if you ask us to delete or stop selling your data, it may impact your experience with us, and you may not be able to participate in certain programs or membership services which require the usage of your personal information to function. But in no circumstances, we will discriminate against you for exercising your rights.
       
      To exercise your California data protection rights described above, please send your request(s) by one of the following means:
       
      By email: <Contact/>
      
<!--      By visiting this page on our website: [chatbro.online/contact](https://chatbro.online/contact)-->

  Your data protection rights, described above, are covered by the CCPA, short for the California Consumer Privacy Act. To find out more, visit the official [California Legislative Information](https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201720180AB375) website. The CCPA took effect on 01/01/2020. 
 
14. <a id="service-providers" href="#service-providers">Service Providers</a>
 
  We may employ third party companies and individuals to facilitate our Services (“**Service Providers**”), provide our Services on our behalf, perform our Service-related services or assist us in analyzing how our Services are used.
   
  These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
 
15. <a id="analytics" href="#analytics">Analytics</a>
 
  We may use third-party Service Providers to monitor and analyze the use of our Services.
   
  **Google Analytics**
  <br/>
  Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Services. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.
   
  For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en
   
  We also encourage you to review the Google's policy for safeguarding your data: https://support.google.com/analytics/answer/6004245.
   
<!--  **Firebase**-->
<!--  <br/>-->
<!--  Firebase is analytics service provided by Google Inc.-->
<!--   -->
<!--  You may opt-out of certain Firebase features through your mobile device settings, such as your device advertising settings or by following the instructions provided by Google in their Privacy Policy: https://policies.google.com/privacy?hl=en-->
<!--   -->
<!--  For more information on what type of information Firebase collects, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en-->
<!--   -->
<!--  **Fathom Analytics**-->
<!--  <br/>-->
<!--  Fathom Analytics is analytics service provided by Conva Ventures Inc. You can find their Privacy Policy here: https://usefathom.com/privacy/-->
<!--   -->
<!--  **Piwik / Matomo**-->
<!--  <br/>-->
<!--  Piwik or Matomo is a web analytics service. You can visit their Privacy Policy page here: https://matomo.org/privacy-policy-->
<!--   -->
<!--  **Clicky**-->
<!--  <br/>-->
<!--  Clicky is a web analytics service. Read the Privacy Policy for Clicky here: https://clicky.com/terms-->
<!--   -->
<!--  **Cloudflare Analytics**-->
<!--  <br/>-->
<!--  Cloudflare analytics is a web analytics service operated by Cloudflare Inc. Read the Privacy Policy here: https://www.cloudflare.com/privacypolicy/ -->
<!--   -->
<!--  **Segment.io**-->
<!--  <br/>-->
<!--  Segment.io is a web traffic analysis tool. You can read the Privacy Policy for Segment.io here: https://segment.com/legal/privacy/.-->
<!--   -->
<!--  **Statcounter**-->
<!--  <br/>-->
<!--  Statcounter is a web traffic analysis tool. You can read the Privacy Policy for Statcounter here: https://statcounter.com/about/legal/-->
<!--   -->
<!--  **Flurry Analytics**-->
<!--  <br/>-->
<!--  Flurry Analytics service is provided by Yahoo! Inc.-->
<!--   -->
<!--  You can opt-out from Flurry Analytics service to prevent Flurry Analytics from using and sharing your information by visiting the Flurry's Opt-out page: https://dev.flurry.com/secure/optOut.do-->
<!--   -->
<!--  For more information on the privacy practices and policies of Yahoo!, please visit their Privacy Policy page: https://legal.yahoo.com/us/en/yahoo/privacy/index.html-->
<!--   -->
<!--  **Mixpanel**-->
<!--  <br/>-->
<!--  Mixpanel is provided by Mixpanel Inc.-->
<!--   -->
<!--  You can prevent Mixpanel from using your information for analytics purposes by opting-out. To opt-out of Mixpanel service, please visit this page: https://mixpanel.com/optout/-->
<!--   -->
<!--  For more information on what type of information Mixpanel collects, please visit the Terms of Use page of Mixpanel: https://mixpanel.com/terms/-->
<!--   -->
<!--  **Unity Analytics**-->
<!--  <br/>-->
<!--  Unity Analytics is provided by Unity Technologies.-->
<!--   -->
<!--  For more information on what type of information Unity Analytics collects, please visit their Privacy Policy page: https://unity3d.com/legal/privacy-policy-->
<!--   -->
<!--  **Ackee**-->
<!--  <br/>-->
<!--  Ackee is a web traffic analysis tool.-->
<!--   -->
<!--  For more information on what type of information Ackee collects, please visit their Terms of Service page: https://electerious.com/terms_of_service.html-->
<!--   -->
<!--  **Simple Analytics**-->
<!--  <br/>-->
<!--  Simple Analytics is a web-based analysis tool-->
<!--   -->
<!--  For more information on what type of information Ackee collects, please visit their Privacy Policy page: https://simpleanalytics.com/privacy-policy-->
<!--   -->
<!--  **PostHog**-->
<!--  <br/>-->
<!--  PostHog is a product analytics platform built for the modern enterprise, with the differentiators of being open source and having a broader view of the tools needed to make a product successful.-->
<!--   -->
<!--  For more information about PostHog, please visit their Privacy Policy: https://posthog.com/privacy-->
<!--   -->
<!--  **Yodo1**-->
<!--  <br/>-->
<!--  Yodo1 is a service provided by Yodo1, Ltd.-->
<!--   -->
<!--  For more information on what type of information Yodo1 collects, please visit their Privacy Policy page: https://www.yodo1.com/privacy-->
<!--   -->
<!--  **Weblate**-->
<!--  <br/>-->
<!--  For more information on what type of information Weblate collects, please visit their Privacy Policy page: https://weblate.org/en/terms/-->
 
16. <a id="ci-cd-tools" href="#ci-cd-tools">CI/CD Tools</a>
 
  We may use third-party Service Providers to automate the development process of our Services. 
   
  **GitHub**
  <br/>
  GitHub is provided by GitHub, Inc.
   
  GitHub is a development platform to host and review code, manage projects, and build software.
   
  For more information on what data GitHub collects for what purpose and how the protection of the data is ensured, please visit GitHub Privacy Policy page: https://help.github.com/en/articles/github-privacy-statement.
   
  **GitLab CI/CD**
  <br/>
  GitLab CI/CD is provided by GitLab, Inc.
   
  GitLab CI (Continuous Integration) service is a part of GitLab that build and test the software whenever developer pushes code to application. 
   
  GitLab CD (Continuous Deployment) is a software service that places the changes of every code in the production which results in every day deployment of production. 
   
  For more information on what data GitLab CI/CD collects for what purpose and how the protection of the data is ensured, please visit GitLab CI/CD Privacy Policy page: https://about.gitlab.com/privacy/.
   
<!--  **Travis CI**-->
<!--  <br/>-->
<!--  Travis CI is a distributed continuous integration service to build and test projects hosted at GitHub.-->
<!--   -->
<!--  For more information on what data Travis CI collects for what purpose and how the protection of the data is ensured, please visit Travis CI Privacy Policy page: https://docs.travis-ci.com/legal/privacy-policy.-->
<!--   -->
<!--  **Bitrise**-->
<!--  <br/>-->
<!--  Bitrise is provided by Bitrise Limited. -->
<!--   -->
<!--  Bitrise is a Continuous Integration and Delivery (CI/CD) Platform as a Service with a main focus on mobile app development (iOS, Android, React Native, Flutter, and so on). -->
<!--   -->
<!--  For more information on what data Bitrise collects for what purpose and how the protection of the data is ensured, please visit Bitrise Privacy Notice page: https://www.bitrise.io/privacy. -->
<!--   -->
<!--  **Fastlane**-->
<!--  <br/>-->
<!--  Fastlane is provided by Google, Inc. -->
<!--   -->
<!--  Fastlane is a continuous delivery tool for iOS and Android apps. -->
<!--   -->
<!--  For more information on what data Fastlane collects for what purpose and how the protection of the data is ensured, please visit the Google Privacy Policy page: https://policies.google.com/privacy. -->
<!--   -->
<!--  **Codacy**-->
<!--  <br/>-->
<!--  Codacy is an automated code analysis/quality tool that helps developers ship better software, faster. -->
<!--   -->
<!--  For more information on what data Codacy collect for what purpose and how the protection of the data is ensured, please visit Codacy Privacy Policy page: https://www.codacy.com/privacy. -->
<!--   -->
<!--  **Codecov**-->
<!--  <br/>-->
<!--  Codecov provides highly integrated tools to group, merge, archive and compare coverage reports. -->
<!--   -->
<!--  For more information on what data Codecov collects for what purpose and how the protection of the data is ensured, please visit their Privacy Policy page: https://codecov.io/privacy. -->
<!--   -->
<!--  **Codemagic**-->
<!--  <br/>-->
<!--  Codemagic is provided by Nevercode LTD.-->
<!--   -->
<!--  Codemagic is the official CI/CD solution dedicated just for Flutter apps.-->
<!--   -->
<!--  For more information on what data Codemagic collects for what purpose and how the protection of the data is ensured, please visit their Terms and conditions page: https://codemagic.io/terms/.-->
<!--   -->
<!--  **Crowdin**-->
<!--  <br/>-->
<!--  Crowdin is a cloud-based solution that streamlines localization management to effectively manage all of your multilingual content. -->
<!--   -->
<!--  For more information on what data Crowdin collects for what purpose and how the protection of the data is ensured, please visit Crowdin Privacy Policy page: https://support.crowdin.com/privacy-policy/. -->
<!--   -->
<!--  **CircleCI**-->
<!--  <br/>-->
<!--  CircleCI is provided by Circle Internet Services, Inc. -->
<!--   -->
<!--  CircleCI is Continuous Integration, a development practice which is being used by software teams allowing them to build, test and deploy applications easier and quicker on multiple platforms. -->
<!--   -->
<!--  For more information on what data Circle CI collects for what purpose and how the protection of the data is ensured, please visit Circle CI Privacy Policy page: https://circleci.com/privacy/. -->
 
<!--16. <a id="advertising" href="#advertising">Advertising</a>-->
<!-- -->
<!--  We may use third-party Service Providers to show advertisements to you to help support and maintain our Services.-->
<!--   -->
<!--  **Google AdSense DoubleClick Cookie**-->
<!--  <br/>-->
<!--  Google, as a third party vendor, uses cookies to serve ads on our Services. Google's use of the DoubleClick cookie enables it and its partners to serve ads to our users based on their visit to our Services or other websites on the Internet.-->
<!--   -->
<!--  You may opt out of the use of the DoubleClick Cookie for interest-based advertising by visiting the Google Ads Settings web page: http://www.google.com/ads/preferences/-->
   
<!--  **Bing Ads**-->
<!--  <br/>-->
<!--  Bing Ads is an advertising service provided by Microsoft Inc.-->
<!--   -->
<!--  You can opt-out from Bing Ads by following the instructions on Bing Ads Opt-out page: https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads-->
<!--   -->
<!--  For more information about Bing Ads, please visit their Privacy Policy: https://privacy.microsoft.com/en-us/PrivacyStatement-->
<!--   -->
<!--  **AdMob by Google**-->
<!--  <br/>-->
<!--  AdMob by Google is provided by Google Inc.-->
<!--   -->
<!--  You can opt-out from the AdMob by Google service by following the instructions described by Google: https://support.google.com/ads/answer/2662922?hl=en-->
<!--   -->
<!--  For more information on how Google uses the collected information, please visit the “How Google uses data when you use our partners' sites or app” page: http://www.google.com/policies/privacy/partners/ or visit the Privacy Policy of Google: http://www.google.com/policies/privacy/-->
<!--   -->
<!--  **AdButler**-->
<!--  <br/>-->
<!--  AdButler is an advertising service provided by Sparklit Networks Inc.-->
<!--  For more information about AdButler, please visit their Privacy Policy: https://www.sparklit.com/agreements.spark?agreement=privacy-->
<!--   -->
<!--  **Unity Ads**-->
<!--  <br/>-->
<!--  Unity Ads is provided by Unity Technologies.-->
<!--   -->
<!--  You can opt-out from Unity Ads service by following the instructions as described by Unity Technologies on their Privacy Policy page: https://unity3d.com/legal/privacy-policy-->
<!--   -->
<!--  For more information about Unity Technologies, please visit Unity Technologies Privacy Policy: https://unity3d.com/legal/privacy-policy-->
 
<!--17. <a id="behavioral-remarketing" href="#behavioral-remarketing">Behavioral Remarketing</a>-->
<!-- -->
<!--  Grainstack uses remarketing services to advertise on third party websites to you after you visited our Services. We and our third-party vendors use cookies to inform, optimize and serve ads based on your past visits to our Services.-->
<!--   -->
<!--  **Google Ads (AdWords)**-->
<!--  <br/>-->
<!--  Google Ads (AdWords) remarketing service is provided by Google Inc.-->
<!--   -->
<!--  You can opt-out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the Google Ads Settings page: http://www.google.com/settings/ads-->
<!--   -->
<!--  Google also recommends installing the Google Analytics Opt-out Browser Add-on – https://tools.google.com/dlpage/gaoptout – for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics.-->
<!--   -->
<!--  For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en-->
<!--   -->
<!--  **Bing Ads Remarketing**-->
<!--  <br/>-->
<!--  Bing Ads remarketing service is provided by Microsoft Inc.-->
<!--   -->
<!--  You can opt-out of Bing Ads interest-based ads by following their instructions: https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads-->
<!--   -->
<!--  You can learn more about the privacy practices and policies of Microsoft by visiting their Privacy Policy page: https://privacy.microsoft.com/en-us/PrivacyStatement-->
<!--   -->
<!--  **Twitter**-->
<!--  <br/>-->
<!--  Twitter remarketing service is provided by Twitter Inc.-->
<!--   -->
<!--  You can opt-out from Twitter's interest-based ads by following their instructions: https://support.twitter.com/articles/20170405-->
<!--   -->
<!--  You can learn more about the privacy practices and policies of Twitter by visiting their Privacy Policy page: https://twitter.com/privacy-->
<!--   -->
<!--  **Facebook**-->
<!--  <br/>-->
<!--  Facebook remarketing service is provided by Facebook Inc.-->
<!--   -->
<!--  You can learn more about interest-based advertising from Facebook by visiting this page: https://www.facebook.com/help/1075880512458213-->
<!--   -->
<!--  To opt-out from Facebook's interest-based ads, follow these instructions from Facebook: https://www.facebook.com/help/247395082112892-->
<!--   -->
<!--  Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the Digital Advertising Alliance in the USA http://www.aboutads.info/choices/, the Digital Advertising Alliance of Canada in Canada http://youradchoices.ca/ or the European Interactive Digital Advertising Alliance in Europe http://www.youronlinechoices.eu/, or opt-out using your mobile device settings.-->
<!--   -->
<!--  For more information on the privacy practices of Facebook, please visit Facebook's Data Policy: https://www.facebook.com/privacy/explanation-->
<!--   -->
<!--  **Pinterest**-->
<!--  <br/>-->
<!--  Pinterest remarketing service is provided by Pinterest Inc.-->
<!--   -->
<!--  You can opt-out from Pinterest's interest-based ads by enabling the “Do Not Track” functionality of your web browser or by following Pinterest instructions: http://help.pinterest.com/en/articles/personalization-and-data-->
<!--   -->
<!--  You can learn more about the privacy practices and policies of Pinterest by visiting their Privacy Policy page: https://about.pinterest.com/en/privacy-policy-->
 
17. <a id="payments" href="#payments">Payments</a>
 
  We may provide paid products and/or services within our Services. In that case, we use third-party services for payment processing (e.g. payment processors).
   
  We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.
   
  The payment processors we work with are:
   
  **PayPal or Braintree**
  <br/>
  Their Privacy Policy can be viewed at https://www.paypal.com/webapps/mpp/ua/privacy-full
   
<!--  **FastSpring**-->
<!--  <br/>-->
<!--  Their Privacy Policy can be viewed at https://fastspring.com/privacy/-->
<!--   -->
<!--  **Apple Store In-App Payments**-->
<!--  <br/>-->
<!--  Their Privacy Policy can be viewed at: https://www.apple.com/legal/privacy/en-ww/ / https://support.apple.com/en-us/HT203027 -->
<!--   -->
<!--  **Google Play In-App Payments**-->
<!--  <br/>-->
<!--  Their Privacy Policy can be viewed at: https://policies.google.com/privacy?hl=en&gl=us / https://payments.google.com/payments/apis-secure/u/0/get_legal_document?ldo=0&ldt=privacynotice&ldl=en -->
   
  **Stripe**
  <br/>
  Their Privacy Policy can be viewed at: https://stripe.com/us/privacy
   
<!--  **2Checkout**-->
<!--  <br/>-->
<!--  Their Privacy Policy can be viewed at: https://www.2checkout.com/legal/privacy/ -->
<!--   -->
<!--  **Adyen**-->
<!--  <br/>-->
<!--  Their Terms and conditions can be viewed at https://www.adyen.com/legal/terms-and-conditions.-->
<!--   -->
<!--  **Alipay**-->
<!--  <br/>-->
<!--  Their Privacy Policy can be viewed at: https://render.alipay.com/p/f/agreementpages/alipayglobalprivacypolicy.html -->
<!--   -->
<!--  **Authorize.net**-->
<!--  <br/>-->
<!--  Their Privacy Policy can be viewed at: https://www.authorize.net/about-us/privacy/ -->
<!--   -->
<!--  **Elavon**-->
<!--  <br/>-->
<!--  Their Privacy Policy can be viewed at: https://www.elavon.com/privacy-pledge.html -->
<!--   -->
<!--  **First Data**-->
<!--  <br/>-->
<!--  Their Privacy Policy can be viewed at: https://www.firstdata.com/en_us/privacy.html -->
<!--   -->
<!--  **Go Cardless**-->
<!--  <br/>-->
<!--  Their Privacy Policy can be viewed at: https://gocardless.com/legal/privacy -->
<!--   -->
<!--  **Klarna**-->
<!--  <br/>-->
<!--  Their Services Terms, Privacy Policy and Buyer Protection Policy can be viewed at https://www.klarna.com/us/legal/.-->
<!--   -->
<!--  **Moneris**-->
<!--  <br/>-->
<!--  Their Privacy Policy can be viewed at: https://www.moneris.com/legal/privacy-policy -->
<!--   -->
<!--  **Plaid**-->
<!--  <br/>-->
<!--  Their End User Privacy Policy, Cookie Policy and Privacy Statement can be viewed at https://plaid.com/legal/.-->
<!--   -->
<!--  **Sage Pay**-->
<!--  <br/>-->
<!--  Their Privacy Policy can be viewed at: https://www.sagepay.co.uk/policies/privacy-policy -->
<!--   -->
<!--  **Square**-->
<!--  <br/>-->
<!--  Their Privacy Policy can be viewed at: https://squareup.com/us/en/legal/general/privacy -->
<!--   -->
<!--  **Verifone**-->
<!--  <br/>-->
<!--  Their Privacy Policy can be viewed at: https://www.verifone.com/en/privacy -->
<!--   -->
<!--  **WePay**-->
<!--  <br/>-->
<!--  Their Privacy Policy can be viewed at: https://go.wepay.com/privacy-policy -->
<!--   -->
<!--  **WorldPay**-->
<!--  <br/>-->
<!--  Their Privacy Policy can be viewed at: https://online.worldpay.com/terms/privacy -->
<!--   -->
<!--  **WeChat**-->
<!--  <br/>-->
<!--  Their Privacy Policy can be viewed at: https://www.wechat.com/en/privacy_policy.html -->
 
18. <a id="links-to-other-sites" href="#links-to-other-sites">Links to Other Sites</a>
 
  Our Services may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
   
  We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
 
19. <a id="childrens-privacy" href="#childrens-privacy">Children's Privacy</a>
 
  Our Services are not intended for use by children under the age of 18 (“**Child**” or “**Children**”).
   
  We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.
 
20. <a id="changes-to-this-privacy-policy" href="#changes-to-this-privacy-policy">Changes to this Privacy Policy</a>
 
  We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
   
  We will let you know via email and/or a prominent notice on our Services, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.
   
  You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
 
21. <a id="contact-us" href="#contact-us">Contact Us</a>
 
  If you have any questions about this Privacy Policy, please contact us:
  <br/> 
  By email: <Contact/>.
   <br/>
<!--  By visiting this page on our website: [chatbro.online/contact](https://chatbro.online/contact).-->
`.trim()

const Privacy = (): any => {
  return (
    <View className={styles.page}>
      <View>
        <MarkdownText>{markdown}</MarkdownText>
      </View>
      <Link className={'link-home'} href={'/'}>
        <Logo />
      </Link>
    </View>
  )
}

export default Privacy
