branch-defaults:
  master:
    environment: agencyai-gg-prod-backend
    group_suffix: null
deploy:
  artifact: artifact.zip
global:
  application_name: agencyai-gg
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
